"""create characters table

Revision ID: 2dbab4d24ffa
Revises: 
Create Date: 2024-08-29 15:58:42.970158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbab4d24ffa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.String(), nullable=True),
    sa.Column('cls_name', sa.String(), nullable=True),
    sa.Column('cls_desc', sa.String(), nullable=True),
    sa.Column('arch_name', sa.String(), nullable=True),
    sa.Column('arch_desc', sa.String(), nullable=True),
    sa.Column('bkd_name', sa.String(), nullable=True),
    sa.Column('bkd_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
