"""rmv clas_desc column

Revision ID: 6b57e5f09733
Revises: 2dbab4d24ffa
Create Date: 2024-08-29 16:09:21.487339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b57e5f09733'
down_revision = '2dbab4d24ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('cls_desc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cls_desc', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
