"""adds is_favorite to Character

Revision ID: 719765622ae2
Revises: 879b808148d3
Create Date: 2024-08-30 16:49:11.489597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719765622ae2'
down_revision = '879b808148d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###
